# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS for the build environment
build:
  os: ubuntu-24.04

  commands:
    # Publish existing public-facing static assets
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp document.html $READTHEDOCS_OUTPUT/html/index.html
    - cp glossary.html $READTHEDOCS_OUTPUT/html/glossary.html
    - cp index.html $READTHEDOCS_OUTPUT/html/calculator.html
    - cp github-finops-cal-image-01.jpg $READTHEDOCS_OUTPUT/html/github-finops-cal-image-01.jpg
        